DO $$ BEGIN
 CREATE TYPE "public"."garment_type" AS ENUM('suit', 'jacket', 'trousers', 'tie', 'pocket_square', 'shirt', 'shoe');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."season" AS ENUM('spring', 'summer', 'fall', 'winter');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "closet-book_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "closet-book_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"outfit_id" integer,
	"date" date NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "closet-book_garment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "closet-book_garment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"type" "garment_type" NOT NULL,
	"color" varchar(7) NOT NULL,
	"quantity" integer NOT NULL,
	"style_season" "season" NOT NULL,
	"weather_season" "season" NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "closet-book_outfit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "closet-book_outfit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"jacket_id" integer,
	"trousers_id" integer,
	"shirt_id" integer,
	"tie_id" integer,
	"pocket_square_id" integer,
	"shoe_id" integer
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_entries" ADD CONSTRAINT "closet-book_entries_outfit_id_closet-book_outfit_id_fk" FOREIGN KEY ("outfit_id") REFERENCES "public"."closet-book_outfit"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_outfit" ADD CONSTRAINT "closet-book_outfit_jacket_id_closet-book_garment_id_fk" FOREIGN KEY ("jacket_id") REFERENCES "public"."closet-book_garment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_outfit" ADD CONSTRAINT "closet-book_outfit_trousers_id_closet-book_garment_id_fk" FOREIGN KEY ("trousers_id") REFERENCES "public"."closet-book_garment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_outfit" ADD CONSTRAINT "closet-book_outfit_shirt_id_closet-book_garment_id_fk" FOREIGN KEY ("shirt_id") REFERENCES "public"."closet-book_garment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_outfit" ADD CONSTRAINT "closet-book_outfit_tie_id_closet-book_garment_id_fk" FOREIGN KEY ("tie_id") REFERENCES "public"."closet-book_garment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_outfit" ADD CONSTRAINT "closet-book_outfit_pocket_square_id_closet-book_garment_id_fk" FOREIGN KEY ("pocket_square_id") REFERENCES "public"."closet-book_garment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "closet-book_outfit" ADD CONSTRAINT "closet-book_outfit_shoe_id_closet-book_garment_id_fk" FOREIGN KEY ("shoe_id") REFERENCES "public"."closet-book_garment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "outfit_id_idx" ON "closet-book_entries" USING btree ("outfit_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "date_idx" ON "closet-book_entries" USING btree ("date");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "garment_type_idx" ON "closet-book_garment" USING btree ("type");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "garment_style_season_idx" ON "closet-book_garment" USING btree ("style_season");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "garment_weather_season_idx" ON "closet-book_garment" USING btree ("weather_season");